# Generated by Django 6.0.3 on 2026-08-12 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenements', '0003_alter_resultat_createur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(max_length=100, unique=True)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telephone', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_billet', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('PRESSE', 'Presse')], default='STANDARD', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('UTILISE', 'Utilisé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('code_unique', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('zones_accessibles', models.JSONField(default=list)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='evenements.evenement')),
                ('spectateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='paiements.spectateur')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billet', to='paiements.transaction')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('CARTE', 'Carte bancaire'), ('MOCK', 'Simulation (dev)')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=20)),
                ('reference_prestataire', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('billet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='paiements.billet')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
