# Generated by Django 6.0.3 on 2026-08-14 10:05


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenements', '0003_alter_resultat_createur'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(max_length=100, unique=True)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telephone', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('place', models.CharField(max_length=50)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenements.evenement')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='sites.zone')),
                ('spectateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='paiements.spectateur')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billet', to='paiements.transaction')),

            ],
        ),
    ]
