# Generated by Django 6.0.3 on 2026-08-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_add_type_billet'),
    ]

    operations = [
    ]
