# Generated by Django 6.0.3 on 2026-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_add_payment_model'),
        ('paiements', '0003_add_payment_model'),
    ]

    operations = [
    ]
