# Generated by Django 6.0.3 on 2026-08-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_merge_0002_add_payment_model_0003_add_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets', to='paiements.transaction'),
        ),
    ]
