# Generated by Django 6.0.3 on 2026-08-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0008_remove_evenement_competiteurs'),
        ('paiements', '0005_alter_billet_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billet',
            options={'ordering': ['-date_commande']},
        ),
        migrations.RemoveField(
            model_name='billet',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='zone',
        ),
        migrations.AddField(
            model_name='billet',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billet',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('UTILISE', 'Utilisé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='billet',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='evenements.evenement'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
