# Generated by Django 6.0.3 on 2026-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0006_alter_billet_options_remove_billet_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code du billet', null=True, upload_to='qr_codes/'),
        ),
    ]
