# Generated by Django 6.1 on 2026-08-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=100)),
                ('pays', models.CharField(choices=[('SN', 'Sénégal'), ('FR', 'France'), ('US', 'États-Unis'), ('JP', 'Japon'), ('OT', 'Autre')], default='SN', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='competiteurs/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competiteurs', to='evenements.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('regle', models.TextField(blank=True)),
                ('accessibilite', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('competiteur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evenements.competiteur')),
                ('nom', models.CharField(max_length=100)),
            ],
            bases=('evenements.competiteur',),
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('competiteur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evenements.competiteur')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
            bases=('evenements.competiteur',),
        ),
        migrations.AddField(
            model_name='categorie',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='evenements.discipline'),
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='evenements.categorie')),
                ('competiteurs', models.ManyToManyField(related_name='evenements', to='evenements.competiteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='sites.site')),
            ],
        ),
    ]
