# Generated by Django 6.0.3 on 2026-08-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_resultat_competiteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='competiteur',
        ),
    ]
