# Generated by Django 6.0.3 on 2026-08-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0005_remove_resultat_competiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='competiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evenements.competiteur'),
        ),
    ]
