# Generated by Django 6.0.3 on 2026-08-13 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0006_resultat_competiteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competiteur',
            name='statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='evenements.evenement'),
        ),
    ]
