# Generated by Django 6.0.3 on 2026-08-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0007_alter_competiteur_statut_alter_resultat_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='competiteurs',
        ),
    ]
