# Generated by Django 6.0.3 on 2026-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0008_remove_evenement_competiteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='competiteur',
            name='pays',
            field=models.CharField(choices=[('SN', 'Sénégal'), ('FR', 'France'), ('US', 'États-Unis'), ('JP', 'Japon'), ('OT', 'Autre')], max_length=2),
        ),
    ]
