# Generated by Django 6.0.3 on 2026-08-12 22:57

import utilisateurs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personnel',
            managers=[
                ('objects', utilisateurs.models.PersonnelManager()),
            ],
        ),
    ]
