# Generated by Django 6.0.3 on 2026-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_personnel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='permissions_app',
            field=models.JSONField(blank=True, default=list, help_text="Liste des permissions de l'utilisateur"),
        ),
    ]
