# Generated by Django 6.1 on 2026-08-13 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actualites', '0001_initial'),
        ('evenements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualite',
            name='evenement_lie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='evenements.evenement'),
        ),
    ]
