# Generated by Django 6.0.3 on 2026-08-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actualites', '0001_initial'),
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='evenement_lie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='evenements.evenement'),
        ),
    ]
