# Generated by Django 6.1 on 2026-08-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_type', models.CharField(choices=[('SPECTATEUR', 'Spectateur'), ('PERSONNEL', 'Personnel')], default='SPECTATEUR', max_length=12)),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('LU', 'Lu'), ('NON_LU', 'Non lu')], default='NON_LU', max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
