# Generated by Django 6.1 on 2026-08-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('LU', 'Lu'), ('NON_LU', 'Non lu')], default='NON_LU', max_length=10)),
                ('spectateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiements.spectateur')),
            ],
        ),
    ]
