# Generated by Django 6.0.3 on 2026-08-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('LU', 'Lu'), ('NON_LU', 'Non lu')], default='NON_LU', max_length=10)),
            ],
        ),
    ]
