# Generated by Django 6.1 on 2026-08-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='spectateur',
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiements.transaction'),
        ),
    ]
