# Generated by Django 6.1 on 2026-08-14 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='personnel',
            field=models.ForeignKey(blank=True, help_text='Obligatoire si destinataire_type = PERSONNEL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_backoffice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='spectateur',
            field=models.ForeignKey(blank=True, help_text='Obligatoire si destinataire_type = SPECTATEUR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiements.spectateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Obligatoire si destinataire_type = SPECTATEUR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiements.transaction'),
        ),
    ]
