# Generated by Django 6.0.3 on 2026-08-14 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_transaction'),
        ('paiements', '0006_alter_billet_options_remove_billet_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire_type',
            field=models.CharField(choices=[('SPECTATEUR', 'Spectateur'), ('PERSONNEL', 'Personnel')], default='SPECTATEUR', max_length=12),
        ),
        migrations.AddField(
            model_name='notification',
            name='personnel',
            field=models.ForeignKey(blank=True, help_text='Obligatoire si destinataire_type = PERSONNEL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_backoffice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='spectateur',
            field=models.ForeignKey(blank=True, help_text='Obligatoire si destinataire_type = SPECTATEUR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiements.spectateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Obligatoire si destinataire_type = SPECTATEUR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiements.transaction'),
        ),
    ]
